### ISSUE TITLE
Connecting to api keys 

### ISSUE THREAD

**Issue by kai9987kai** [JokerMartini/max-gpt#3]
Hiya there seems to be a issue with connecting to api keys is this just me??

**Comment by kai9987kai** [comment]
**### managed to get the errors:**



Traceback (most recent call last):
  File "C:\Users\molz\OneDrive\Desktop\max-gpt-main\max-gpt-main\max-gpt\contents\main.py", line 285, in fetch_request
    self.ai.fetch_command(self.uiInput.toPlainText(), language=self.uiLanauge.currentText())
  File "C:\Users\molz\OneDrive\Desktop\max-gpt-main\max-gpt-main\max-gpt\contents\main.py", line 112, in fetch_command
    resp = openai.ChatCompletion.create(
  File "C:\Users\molz\OneDrive\Desktop\max-gpt-main\max-gpt-main\max-gpt\contents\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\molz\OneDrive\Desktop\max-gpt-main\max-gpt-main\max-gpt\contents\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\molz\OneDrive\Desktop\max-gpt-main\max-gpt-main\max-gpt\contents\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\molz\OneDrive\Desktop\max-gpt-main\max-gpt-main\max-gpt\contents\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\molz\OneDrive\Desktop\max-gpt-main\max-gpt-main\max-gpt\contents\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Your account is not active, please check your billing details on our website.

**Comment by kai9987kai** [comment]
was my open ai account billing problem turns out
